# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('up_date', models.DateField(default=datetime.datetime(2017, 4, 3, 7, 56, 52, 237000, tzinfo=utc))),
                ('file_url', models.CharField(max_length=200)),
                ('file_self', models.FileField(upload_to=b'')),
                ('is_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_use', models.BooleanField(default=True)),
            ],
        ),
    ]
