# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webdisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_self',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='files',
            name='up_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 3, 9, 25, 56, 960000, tzinfo=utc)),
        ),
    ]
